image: Visual Studio 2017

configuration: 
  - Relase 
  
clone_folder: c:\projects\sc

platform:
- x86
- x64

install:
  - cd c:\projects\sc
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017" ..

build_script:
  - cmake -DBUILD_SHARED_LIBS=ON .
  - cmake --build .
  - cmake -DBUILD_SHARED_LIBS=OFF .
  - cmake --build .
