language : cpp
    
matrix:
  include:
    - os: osx
      osx_image: xcode8
      compiler: clang
    - os: linux
      env: CLANG_VERSION=5.0 BUILD_TYPE=Release
      addons: &clang5
        apt:
          packages:
            - g++-6
            - clang-5.0
            - libx11-dev
            - libxfixes-dev 
            - libxtst-dev
          sources: 
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
      
before_install:
  - if [[ -n "$CLANG_VERSION" ]]; then export CXX=clang++-$CLANG_VERSION CC=clang-$CLANG_VERSION; fi
  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz"
      mkdir -p ${TRAVIS_BUILD_DIR}/deps/cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C ${TRAVIS_BUILD_DIR}/deps/cmake
      export PATH="${TRAVIS_BUILD_DIR}/deps/cmake/bin:${PATH}";
    else
      brew update && brew upgrade cmake || brew install cmake;
      brew install gcc
    fi
  
script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_C_COMPILER="$CC" . && make;
  
notifications:
  email: false
